"use client";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function ChessLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        <header className="bg-gray-800 text-white py-4 px-6">
          <nav className="flex justify-between">
            <div>
              <Link className="text-2xl font-semibold" href="/">
                ChessApp
              </Link>
            </div>
            <div>
              <Link
                className="mr-5 hover:text-gray-400"
                href="/chess/add_match"
              >
                Add Match
              </Link>
              <Link className="hover:text-gray-400" href="/chess/leaderboard">
                Leaderboard
              </Link>
              <Link className="hover:text-gray-400" href="/chess/leaderboard">
                Leaderboard
              </Link>
            </div>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
