"use client";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function ChessLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        <header className="bg-gray-800 text-white py-4 px-6">
          <nav className="flex flex-wrap justify-between">
            <div className="w-full md:w-auto">
              <div className="text-2xl font-semibold">Chess App</div>
            </div>
            <div className="w-full md:w-auto mt-4 md:mt-0 flex justify-between md:space-x-5">
              <Link className="hover:text-gray-400" href={"/chess/add_match"}>
                Add Match
              </Link>
              <Link className="hover:text-gray-400" href={"/chess/leaderboard"}>
                Leaderboard
              </Link>
              <Link className="hover:text-gray-400" href={"/chess/log"}>
                Logs
              </Link>
            </div>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
